### ISSUE TITLE
Ingress_helper.sh does not allow -a switch as AAC codec is experimental

### ISSUE THREAD

**Issue by Hugo14453** [SubliminalHQ/groupwatch#11]

**Comment by sn0w** [comment]
The AAC codec has reached a stable state in december 2015.

Please make sure that FFMPEG 2.8 or higher is installed.
On Ubuntu you might want to use a PPA for that.

<hr>

![](https://cdn.lks.li/vrbds9YSlM.png)

**Comment by sn0w** [comment]
Btw: This might be related to an old version of Ubuntu/Debian.
On Ubuntu Yakkety a recent version is available right from the package manager.

![](https://cdn.lks.li/6tRqAOuufY.png)
